config/routes.rb
ShopifyContestapp::Application.routes.draw do
  resources :accounts
  get "dashboard/index"

  root "dashboard#index"

  resources :accounts do
    member do
      get 'test_connection'
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
    validates_presence_of :shopify_account_url
    validates_presence_of :shopify_api_key
    validates_presence_of :shopify_password
    validates_presence_of :shopify_shared_secret
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account
  before_action :require_login

  # GET /account
  def edit
  end

  # PATCH/PUT /account
  def update
    # See if they are upgrading to Paid
    shopify_service = ShopifyIntegration.new(url: @account.shopify_account_url,
                                             password: @account.shopify_password,
                                             account_id: @account.id)

    shopify_service.connect

    if params[:account][:paid] == true || params[:account][:paid].to_i == 1
      if @account.paid?
        render 'edit'
      else
        # TODO: set the flag to false to really charge the card
        redirect_to shopify_service.create_charge(1, true)
      end
    else
      # If not, just re-render the form
      if shopify_service.delete_charge(@account.charge_id)
        puts "asdfasdfsdfasdfsdfasdfsdfsdf"
        @account.update_attribute(:paid, false)
      end

      render 'edit'
    end
  end

  private

  def set_account
    @account = current_account
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account, :html => { :class => "form-horizontal account" } do |f| %>

  <% if @account.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :shopify_account_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopify_account_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopify_account_url) %>
  </div>
  <div class="form-group">
    <%= f.label :shopify_api_key, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopify_api_key, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopify_api_key) %>
  </div>
  <div class="form-group">
    <%= f.label :shopify_password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopify_password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopify_password) %>
  </div>
  <div class="form-group">
    <%= f.label :shopify_shared_secret, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopify_shared_secret, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopify_shared_secret) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                accounts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/accounts/edit.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:shopify_account_url) %></th>
      <th><%= model_class.human_attribute_name(:shopify_api_key) %></th>
      <th><%= model_class.human_attribute_name(:shopify_password) %></th>
      <th><%= model_class.human_attribute_name(:shopify_shared_secret) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.id, account_path(account) %></td>
        <td><%= account.shopify_account_url %></td>
        <td><%= account.shopify_api_key %></td>
        <td><%= account.shopify_password %></td>
        <td><%= account.shopify_shared_secret %></td>
        <td><%=l account.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_account_path(account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      account_path(account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_account_path,
            :class => 'btn btn-primary' %>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:shopify_account_url) %>:</strong></dt>
  <dd><%= @account.shopify_account_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shopify_api_key) %>:</strong></dt>
  <dd><%= @account.shopify_api_key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shopify_password) %>:</strong></dt>
  <dd><%= @account.shopify_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shopify_shared_secret) %>:</strong></dt>
  <dd><%= @account.shopify_shared_secret %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              accounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_account_path(@account), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              account_path(@account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
              
<%= link_to "Test Connection", test_connection_account_path(@account), :class => 'btn' %>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ShopifyContestapp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ShopifyContestapp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Accounts", accounts_path%></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>